{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://github.com/xiaoqx/pocs/tree/master/opencv/dos-by-assert",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/opencv/opencv/issues/10998",
            "tags": [
              "x_refsource_MISC",
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-05T06:31:05.064Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "cvssV3_1": {
              "scope": "UNCHANGED",
              "version": "3.1",
              "baseScore": 7.5,
              "attackVector": "NETWORK",
              "baseSeverity": "HIGH",
              "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "integrityImpact": "NONE",
              "userInteraction": "NONE",
              "attackComplexity": "LOW",
              "availabilityImpact": "HIGH",
              "privilegesRequired": "NONE",
              "confidentialityImpact": "NONE"
            }
          },
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2018-7712",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-07-23T19:15:21.682722Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:opencv:opencv:3.4.1:*:*:*:*:*:*:*"
            ],
            "vendor": "opencv",
            "product": "opencv",
            "versions": [
              {
                "status": "affected",
                "version": "3.4.1"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "problemTypes": [
          {
            "descriptions": [
              {
                "lang": "en",
                "type": "CWE",
                "cweId": "CWE-617",
                "description": "CWE-617 Reachable Assertion"
              }
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-07-23T19:15:59.030Z"
        }
      }
    ],
    "cna": {
      "tags": [
        "disputed"
      ],
      "affected": [
        {
          "vendor": "n/a",
          "product": "n/a",
          "versions": [
            {
              "status": "affected",
              "version": "n/a"
            }
          ]
        }
      ],
      "datePublic": "2018-03-05T00:00:00",
      "references": [
        {
          "url": "https://github.com/xiaoqx/pocs/tree/master/opencv/dos-by-assert",
          "tags": [
            "x_refsource_MISC"
          ]
        },
        {
          "url": "https://github.com/opencv/opencv/issues/10998",
          "tags": [
            "x_refsource_MISC"
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "The validateInputImageSize function in modules/imgcodecs/src/loadsave.cpp in OpenCV 3.4.1 allows remote attackers to cause a denial of service (assertion failure) because (size.height <= (1<<20)) may be false. Note: \u201cOpenCV CV_Assert is not an assertion (C-like assert()), it is regular C++ exception which can raised in case of invalid or non-supported parameters."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "text",
              "description": "n/a"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "shortName": "mitre",
        "dateUpdated": "2020-01-29T15:03:53"
      },
      "x_legacyV4Record": {
        "affects": {
          "vendor": {
            "vendor_data": [
              {
                "product": {
                  "product_data": [
                    {
                      "version": {
                        "version_data": [
                          {
                            "version_value": "n/a"
                          }
                        ]
                      },
                      "product_name": "n/a"
                    }
                  ]
                },
                "vendor_name": "n/a"
              }
            ]
          }
        },
        "data_type": "CVE",
        "references": {
          "reference_data": [
            {
              "url": "https://github.com/xiaoqx/pocs/tree/master/opencv/dos-by-assert",
              "name": "https://github.com/xiaoqx/pocs/tree/master/opencv/dos-by-assert",
              "refsource": "MISC"
            },
            {
              "url": "https://github.com/opencv/opencv/issues/10998",
              "name": "https://github.com/opencv/opencv/issues/10998",
              "refsource": "MISC"
            }
          ]
        },
        "data_format": "MITRE",
        "description": {
          "description_data": [
            {
              "lang": "eng",
              "value": "** DISPUTED ** The validateInputImageSize function in modules/imgcodecs/src/loadsave.cpp in OpenCV 3.4.1 allows remote attackers to cause a denial of service (assertion failure) because (size.height <= (1<<20)) may be false. Note: \u201cOpenCV CV_Assert is not an assertion (C-like assert()), it is regular C++ exception which can raised in case of invalid or non-supported parameters.\u201d"
            }
          ]
        },
        "problemtype": {
          "problemtype_data": [
            {
              "description": [
                {
                  "lang": "eng",
                  "value": "n/a"
                }
              ]
            }
          ]
        },
        "data_version": "4.0",
        "CVE_data_meta": {
          "ID": "CVE-2018-7712",
          "STATE": "PUBLIC",
          "ASSIGNER": "cve@mitre.org"
        }
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2018-7712",
    "state": "PUBLISHED",
    "dateUpdated": "2024-08-05T06:31:05.064Z",
    "dateReserved": "2018-03-05T00:00:00",
    "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
    "datePublished": "2018-03-05T23:00:00",
    "assignerShortName": "mitre"
  },
  "dataVersion": "5.1"
}