{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://jira.mongodb.org/browse/SERVER-39481",
            "tags": [
              "x_refsource_CONFIRM",
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-05T03:00:19.094Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2019-20923",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "none"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-04-22T17:28:47.037349Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:mongodb:mongodb_server:4.0:*:*:*:*:*:*:*"
            ],
            "vendor": "mongodb",
            "product": "mongodb_server",
            "versions": [
              {
                "status": "affected",
                "version": "4.0"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-04-22T17:27:07.190Z"
        }
      }
    ],
    "cna": {
      "title": "Crash while handling internal Javascript exception types",
      "source": {
        "discovery": "INTERNAL"
      },
      "metrics": [
        {
          "format": "CVSS",
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 6.5,
            "attackVector": "NETWORK",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "LOW",
            "confidentialityImpact": "NONE"
          },
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ]
        }
      ],
      "affected": [
        {
          "vendor": "MongoDB Inc.",
          "product": "MongoDB Server",
          "versions": [
            {
              "status": "affected",
              "version": "4.0",
              "lessThan": "4.0.7",
              "versionType": "custom"
            }
          ],
          "defaultStatus": "unaffected"
        }
      ],
      "datePublic": "2020-11-30T00:00:00.000Z",
      "references": [
        {
          "url": "https://jira.mongodb.org/browse/SERVER-39481",
          "tags": [
            "x_refsource_CONFIRM"
          ]
        }
      ],
      "x_generator": {
        "engine": "Vulnogram 0.0.9"
      },
      "descriptions": [
        {
          "lang": "en",
          "value": "A user authorized to perform database queries may trigger denial of service by issuing specially crafted queries, which throw unhandled Javascript exceptions containing types intended to be scoped to the Javascript engine's internals. This issue affects MongoDB Server v4.0 versions prior to 4.0.7.\n\n",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "<p>A user authorized to perform database queries may trigger denial of service by issuing specially crafted queries, which throw unhandled Javascript exceptions containing types intended to be scoped to the Javascript engine's internals. This issue affects MongoDB Server v4.0 versions prior to 4.0.7.</p>",
              "base64": false
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-749",
              "description": "CWE-749 Exposed Dangerous Method or Function"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
        "shortName": "mongodb",
        "dateUpdated": "2024-01-23T15:01:36.205Z"
      },
      "x_legacyV4Record": {
        "impact": {
          "cvss": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 6.5,
            "attackVector": "NETWORK",
            "baseSeverity": "MEDIUM",
            "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
            "integrityImpact": "NONE",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "LOW",
            "confidentialityImpact": "NONE"
          }
        },
        "source": {
          "discovery": "INTERNAL"
        },
        "affects": {
          "vendor": {
            "vendor_data": [
              {
                "product": {
                  "product_data": [
                    {
                      "version": {
                        "version_data": [
                          {
                            "version_name": "4.0",
                            "version_value": "4.0.7",
                            "version_affected": "<"
                          }
                        ]
                      },
                      "product_name": "MongoDB Server"
                    }
                  ]
                },
                "vendor_name": "MongoDB Inc."
              }
            ]
          }
        },
        "data_type": "CVE",
        "generator": {
          "engine": "Vulnogram 0.0.9"
        },
        "references": {
          "reference_data": [
            {
              "url": "https://jira.mongodb.org/browse/SERVER-39481",
              "name": "https://jira.mongodb.org/browse/SERVER-39481",
              "refsource": "CONFIRM"
            }
          ]
        },
        "data_format": "MITRE",
        "description": {
          "description_data": [
            {
              "lang": "eng",
              "value": "A user authorized to perform database queries may trigger denial of service by issuing specially crafted queries, which throw unhandled Javascript exceptions containing types intended to be scoped to the Javascript engine's internals. This issue affects: MongoDB Inc. MongoDB Server v4.0 versions prior to 4.0.7."
            }
          ]
        },
        "problemtype": {
          "problemtype_data": [
            {
              "description": [
                {
                  "lang": "eng",
                  "value": "CWE-749 Exposed Dangerous Method or Function"
                }
              ]
            }
          ]
        },
        "data_version": "4.0",
        "CVE_data_meta": {
          "ID": "CVE-2019-20923",
          "STATE": "PUBLIC",
          "TITLE": "Crash while handling internal Javascript exception types",
          "ASSIGNER": "cna@mongodb.com",
          "DATE_PUBLIC": "2020-11-30T14:00:00.000Z"
        }
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2019-20923",
    "state": "PUBLISHED",
    "dateUpdated": "2024-08-15T17:19:26.516Z",
    "dateReserved": "2020-10-06T00:00:00",
    "assignerOrgId": "a39b4221-9bd0-4244-95fc-f3e2e07f1deb",
    "datePublished": "2020-11-30T00:00:00",
    "assignerShortName": "mongodb"
  },
  "dataVersion": "5.1"
}