{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://huntr.com/bounties/e536310e-abe7-4585-9cf6-21f77390a5e8",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/lunary-ai/lunary/commit/d8e2e73efd53ab4e92cf47bbf4b639a9f08853d2",
            "tags": [
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-01T18:56:22.480Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-1902",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "yes"
                  },
                  {
                    "Technical Impact": "partial"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-07-31T20:42:52.325488Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:lunary-ai:lunary:*:*:*:*:*:*:*:*"
            ],
            "vendor": "lunary-ai",
            "product": "lunary",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "lessThan": "1.2.8",
                "versionType": "custom"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-07-31T20:47:13.490Z"
        }
      }
    ],
    "cna": {
      "title": "Session Reuse Vulnerability in lunary-ai/lunary",
      "source": {
        "advisory": "e536310e-abe7-4585-9cf6-21f77390a5e8",
        "discovery": "EXTERNAL"
      },
      "metrics": [
        {
          "cvssV3_0": {
            "scope": "UNCHANGED",
            "version": "3.0",
            "baseScore": 7.5,
            "attackVector": "NETWORK",
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
            "integrityImpact": "HIGH",
            "userInteraction": "NONE",
            "attackComplexity": "LOW",
            "availabilityImpact": "NONE",
            "privilegesRequired": "NONE",
            "confidentialityImpact": "NONE"
          }
        }
      ],
      "affected": [
        {
          "vendor": "lunary-ai",
          "product": "lunary-ai/lunary",
          "versions": [
            {
              "status": "affected",
              "version": "unspecified",
              "lessThan": "1.2.8",
              "versionType": "custom"
            }
          ]
        }
      ],
      "references": [
        {
          "url": "https://huntr.com/bounties/e536310e-abe7-4585-9cf6-21f77390a5e8"
        },
        {
          "url": "https://github.com/lunary-ai/lunary/commit/d8e2e73efd53ab4e92cf47bbf4b639a9f08853d2"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "lunary-ai/lunary is vulnerable to a session reuse attack, allowing a removed user to change the organization name without proper authorization. The vulnerability stems from the lack of validation to check if a user is still part of an organization before allowing them to make changes. An attacker can exploit this by using an old authorization token to send a PATCH request, modifying the organization's name even after being removed from the organization. This issue is due to incorrect synchronization and affects the orgs.patch route."
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-821",
              "description": "CWE-821 Incorrect Synchronization"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
        "shortName": "@huntr_ai",
        "dateUpdated": "2024-04-16T11:10:33.420Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-1902",
    "state": "PUBLISHED",
    "dateUpdated": "2024-08-01T18:56:22.480Z",
    "dateReserved": "2024-02-26T19:31:07.972Z",
    "assignerOrgId": "c09c270a-b464-47c1-9133-acb35b22c19a",
    "datePublished": "2024-04-10T17:08:05.267Z",
    "assignerShortName": "@huntr_ai"
  },
  "dataVersion": "5.1"
}