{
  "dataType": "CVE_RECORD",
  "containers": {
    "adp": [
      {
        "title": "CVE Program Container",
        "references": [
          {
            "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-recipe-xss-jfsa-2024-000631930/",
            "tags": [
              "x_transferred"
            ]
          },
          {
            "url": "https://github.com/mlflow/mlflow/pull/10873",
            "tags": [
              "x_transferred"
            ]
          }
        ],
        "providerMetadata": {
          "orgId": "af854a3a-2127-422b-91ae-364da2661108",
          "shortName": "CVE",
          "dateUpdated": "2024-08-02T00:27:59.403Z"
        }
      },
      {
        "title": "CISA ADP Vulnrichment",
        "metrics": [
          {
            "other": {
              "type": "ssvc",
              "content": {
                "id": "CVE-2024-27132",
                "role": "CISA Coordinator",
                "options": [
                  {
                    "Exploitation": "poc"
                  },
                  {
                    "Automatable": "no"
                  },
                  {
                    "Technical Impact": "total"
                  }
                ],
                "version": "2.0.3",
                "timestamp": "2024-08-14T15:25:41.784263Z"
              }
            }
          }
        ],
        "affected": [
          {
            "cpes": [
              "cpe:2.3:a:lfprojects:mlflow:*:*:*:*:*:*:*:*"
            ],
            "vendor": "lfprojects",
            "product": "mlflow",
            "versions": [
              {
                "status": "affected",
                "version": "0",
                "versionType": "python",
                "lessThanOrEqual": "2.9.2"
              }
            ],
            "defaultStatus": "unknown"
          }
        ],
        "providerMetadata": {
          "orgId": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
          "shortName": "CISA-ADP",
          "dateUpdated": "2024-08-14T15:27:31.147Z"
        }
      }
    ],
    "cna": {
      "title": "Insufficient sanitization in MLflow leads to XSS when running an untrusted recipe.",
      "source": {
        "discovery": "EXTERNAL"
      },
      "metrics": [
        {
          "format": "CVSS",
          "cvssV3_1": {
            "scope": "UNCHANGED",
            "version": "3.1",
            "baseScore": 7.5,
            "attackVector": "NETWORK",
            "baseSeverity": "HIGH",
            "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
            "integrityImpact": "HIGH",
            "userInteraction": "REQUIRED",
            "attackComplexity": "HIGH",
            "availabilityImpact": "HIGH",
            "privilegesRequired": "NONE",
            "confidentialityImpact": "HIGH"
          },
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ]
        }
      ],
      "affected": [
        {
          "versions": [
            {
              "status": "affected",
              "version": "0",
              "versionType": "python",
              "lessThanOrEqual": "2.9.2"
            }
          ],
          "packageName": "mlflow",
          "collectionURL": "https://pypi.org/project/pip"
        }
      ],
      "references": [
        {
          "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-recipe-xss-jfsa-2024-000631930/"
        },
        {
          "url": "https://github.com/mlflow/mlflow/pull/10873"
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "value": "Insufficient sanitization in MLflow leads to XSS when running an untrusted recipe.\n\nThis issue leads to a client-side RCE when running an untrusted recipe in Jupyter Notebook.\n\nThe vulnerability stems from lack of sanitization over template variables.\n\n",
          "supportingMedia": [
            {
              "type": "text/html",
              "value": "<p>Insufficient sanitization in MLflow leads to XSS when running an untrusted recipe.</p><p>This issue leads to a client-side RCE when running an untrusted recipe in Jupyter Notebook.</p><p>The vulnerability stems from lack of sanitization over template variables.</p>",
              "base64": false
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "lang": "en",
              "type": "CWE",
              "cweId": "CWE-79",
              "description": "CWE-79 Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "48a46f29-ae42-4e1d-90dd-c1676c1e5e6d",
        "shortName": "JFROG",
        "dateUpdated": "2024-02-23T21:58:59.869Z"
      }
    }
  },
  "cveMetadata": {
    "cveId": "CVE-2024-27132",
    "state": "PUBLISHED",
    "dateUpdated": "2024-08-14T15:28:19.332Z",
    "dateReserved": "2024-02-20T11:10:51.334Z",
    "assignerOrgId": "48a46f29-ae42-4e1d-90dd-c1676c1e5e6d",
    "datePublished": "2024-02-23T21:58:59.869Z",
    "assignerShortName": "JFROG"
  },
  "dataVersion": "5.1"
}